### ISSUE TITLE
[Bug] Error message when loading game

### ISSUE THREAD

**Issue by ScotlandFinest** [redphx/better-xcloud#312] opened 2024-03-21 16:55 UTC
**Platform**
 - Device: samsung galaxy tab s8 ultra.
 - OS: , Android,
 - Browser: Kiwi...
 - Browser Version: 124.0.6327.1
 - Better xCloud Version: 3.2.4

**Describe the bug**
worked fine for several weeks but today every time i try to play a game I get the message: We'll be right back. Sorry we're working on fixing the issues 

Here is a picture of error showing on tampermomkey extension. 
![20240321_165438](https://github.com/redphx/better-xcloud/assets/164387228/6ef75acd-aa9e-4788-9e53-61374f069bc9)

**Screenshots/Videos**
If applicable, add screenshots/videos to help explain your problem.
![20240321_165430](https://github.com/redphx/better-xcloud/assets/164387228/c9a259d9-3ec7-47b0-98ec-e3aefd074e49)
![20240321_165424](https://github.com/redphx/better-xcloud/assets/164387228/bad83434-3157-4ba1-8360-cadf75625dfc)

**Comment by ScotlandFinest** [comment] 2024-03-21 17:05
Cloud gaming works fine on Google chrome and your new Web app.

**Comment by KingNothing81** [comment] 2024-03-21 17:13
Also happend to me. Changing the user agent in the script's settings solved the issue for me.

I think this is caused by the last update to Kiwi Browser. Since that update Kiwi changed it's user agent string to report Chrome 124. But stable Chrome is on 123. So maybe the xCloud page considers this an unsupported browser now.

More details here:
https://github.com/kiwibrowser/src.next/issues/1099

But @redphx: You don't have to downgrade Kiwi to solve this, as recommended on Telegram. Changing user agent also fixes this. But when using one of the other profiles, Kiwi did not auto switch to full screen anymore when starting a game. So I copied and pasted the standard UA string that is shown in the WebView based Android app. And now everything is also working fine with Kiwi again. 

So to fix this issue it should be enough to just override the default UA string of Kiwi.

**Comment by marlonvictor3161M** [comment] 2024-03-21 17:17
The same thing is happening, with me in the Kiwi browser the Xbox logo appears and then the message appears

**Comment by ScotlandFinest** [comment] 2024-03-21 17:23
> Also happend to me. Changing the user agent in the script's settings solved the issue for me.
> 
> I think this is caused by the last update to Kiwi Browser. Since that update Kiwi changed it's user agent string to report Chrome 124. But stable Chrome is on 123. So maybe the xCloud page considers this an unsupported browser now.
> 
> More details here: [kiwibrowser/src.next#1099](https://github.com/kiwibrowser/src.next/issues/1099)
> 
> But @redphx: You don't have to downgrade Kiwi to solve this, as recommended on Telegram. Changing user agent also fixes this. But when using one of the other profiles, Kiwi did not auto switch to full screen anymore when starting a game. So I copied and pasted the standard UA string that is shown in the WebView based Android app. And now everything is also working fine with Kiwi again.
> 
> So to fix this issue it should be enough to just override the default UA string of Kiwi.

---

Hey, thanks for letting me know. I have no idea what a user agent is tbh so no idea how to change it!

**Comment by KingNothing81** [comment] 2024-03-21 17:27
@ScotlandFinest: It's the option at the very bottom of the "Better xCloud" settings. It defaults to "Standard", but you can also use "Windows + Edge" for example. Or as mentioned, open the Android app and copy the UA string that is shown there. Then select "Custom" for the UA string in Kiwi and paste it in. Should also work.

https://better-xcloud.github.io/features/#change-user-agent

**Comment by ScotlandFinest** [comment] 2024-03-21 17:28
Amazing thank you!

FYI found this too:
https://www.reddit.com/r/xcloud/s/nKOQwaUMjC

**Comment by marlonvictor3161M** [comment] 2024-03-21 17:35
![IMG-20240321-WA0007](https://github.com/redphx/better-xcloud/assets/164389993/2f71fd08-e1b0-496a-a714-7b383777066c)
 Bug resolved

**Comment by redphx** [comment] 2024-03-21 21:39
Fixed in 3.2.5

**Closed as completed by redphx** 2024-03-21 21:39 UTC
Labels: bug
