### ISSUE TITLE
We'll be right back. Sorry we're working on fixing the issues

### ISSUE THREAD

**Issue by marlonvictor3161M** [redphx/better-xcloud#313] opened 2024-03-21 17:14 UTC
**
 - Device: Phone, MOTO E20 ANDROID 11.
 -Android, 
 - Browser:  Kiwi browser 
 - Browser Version:
 - Better xCloud Version:  v3.2.4

**Describe the bug** I don't start Fortnite, and other games, the Xbox logo appears and then the message appears: We'll be right back. Sorry we're working on fixing the issues
...
And only the Kiwi browser has this problem, Chrome doesn't have this bug
**Screenshots/Videos**
![IMG-20240321-WA0002](https://github.com/redphx/better-xcloud/assets/164389993/c1910669-f132-4788-bb43-39c634a9fc8e)

If applicable, add screenshots/videos to help explain your problem.

**Comment by KingNothing81** [comment] 2024-03-21 17:19
That's a duplicate of this.
https://github.com/redphx/better-xcloud/issues/312

Please read my post. It should solve that issue.
https://github.com/redphx/better-xcloud/issues/312#issuecomment-2013083064

**Closed as not planned** 2024-03-21 20:45 UTC
Labels: bug
