### ISSUE TITLE
Version 6.0 Beta

### ISSUE THREAD

**Issue by redphx** [redphx/better-xcloud#577] opened 2024-12-03 14:12 UTC
> [!WARNING]
> You will lose all your current settings after installing this version. Backup manually before trying it.

### Android
- Open App settings > Better xCloud script variant > Beta

### Browser
- Install [this version](https://github.com/redphx/better-xcloud/raw/refs/heads/typescript/dist/better-xcloud.user.js)

## How to uninstall
If you wish to return to stable version (5.9.x), do the following steps:

### Android
- Clear app data

### Browser
1. Open Better xCloud settings > scroll to the bottom > Clear data. Do NOT refresh the page.
2. Close xCloud tab
3. Re-install Better xCloud script on the home page

## Changes in version 6.0
- Refactor a lot of features
- Optimize UI and performance

### Added
- Add indicator for controller-friendly select boxes
- Add keyboard shortcuts manager feature
- Add "Virtual controller slot" option (for co-op)
- Add option to disable "Stream your own game" feature
- Add ability to customize different settings for different controllers
- Add "Force Native Mouse & Keyboard for these games" list. It will show empty list at first, refresh the page and it will show.

### Changes
- Update settings UI
- Allow toggling local co-op support without having to refresh the page
- Optimize

### Removed
- Remove "Loading screen > Show game art" (always show game art in Loading screen)

### Screenshots

<img width="507" alt="image" src="https://github.com/user-attachments/assets/79e6776b-51ed-459c-8533-b2b9a237e087">

<img width="502" alt="image" src="https://github.com/user-attachments/assets/b83d01f1-460c-439d-9e25-e20df4d2640c">

<img width="492" alt="image" src="https://github.com/user-attachments/assets/82f471c8-8c59-4d2f-b125-898304528ab3">

<img width="480" alt="image" src="https://github.com/user-attachments/assets/18dca926-08e7-486b-acbf-c957118ad00f">

### How to report bug
Include these info:  
- Device
- Script/Browser
- Screenshot/Video

**Comment by KingNothing81** [comment] 2024-12-04 02:03
Device: Nvidia Shield TV (Android TV 11)
BxC Android App 0.22.0

Hi …

First a big thank you for all your efforts to keep improving “Better xCloud”.

Giving the 6.0 beta version a try, I discovered two controller related issues:

- After opening the Xbox Guide menu with the controller, it’s not possible to navigate and/or close the Guide using the controller. As the controller input seems to be ignored. But it’s still possible to interact and close the Guide menu with the Android TV remote. 

- Same issue happens when using my controller shortcut to open the Stream menu (a.k.a. three dot menu). Like with the Guide menu, it doesn’t react to controller input. Only using the remote works to close it and get back to gaming.

Thanks.

**Comment by redphx** [comment] 2024-12-04 14:38
@KingNothing81 fixed in 6.0.0-beta-2. Thanks for reporting.

**Comment by btncua** [comment] 2024-12-04 18:45
- Device: Desktop
- Script/Browser: Better xCloud 6.0.0-beta-2/Chrome 131.0.6778.109

Virtual controller activation button is not in center of screen. And thanks for update

- Screenshot/Video:
![2024-12-04](https://github.com/user-attachments/assets/bb4dd691-4b29-4c67-afef-ab4df5ab4582)
_Or this a planned change?_

**Comment by KingNothing81** [comment] 2024-12-04 21:21
> @KingNothing81 fixed in 6.0.0-beta-2. Thanks for reporting.

Thanks for the quick fix.

But after updating to 6.0.0-beta-2, I noticed that the “Mouse & Keyboard” tab is visible now in my BxC settings. 

With the first beta and previous versions, the tab was always hidden for me. But I’m not sure what is the expected behavior here and in which cases the tab should be visible for the user or not. So maybe not seeing the tab was indeed a bug in previous versions?

![IMG_0286](https://github.com/user-attachments/assets/cb2eadad-def7-47cf-8794-1d087500dc50)

**Comment by redphx** [comment] 2024-12-04 21:36
@btncua @KingNothing81 both changes are intended

**Comment by redphx** [comment] 2024-12-05 00:29
6.0.0-beta-3: added `1080p (HQ)` option to play with higher bitrate  

<img width="441" alt="image" src="https://github.com/user-attachments/assets/ce8a4aa2-91b4-4529-8969-58c403dc8d66">

**Comment by btncua** [comment] 2024-12-05 14:57
> @btncua @KingNothing81 both changes are intended

Ok, it's a matter of habit)

> 6.0.0-beta-3: added `1080p (HQ)` option to play with higher bitrate
> 
> <img alt="image" width="441" src="https://private-user-images.githubusercontent.com/96280/392609468-ce8a4aa2-91b4-4529-8969-58c403dc8d66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MDk5NDEsIm5iZiI6MTczMzQwOTY0MSwicGF0aCI6Ii85NjI4MC8zOTI2MDk0NjgtY2U4YTRhYTItOTFiNC00NTI5LTg5NjktNThjNDAzZGM4ZDY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDE0NDA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyNjg0YWI1MGRiMmM4ZGUwMGYxZjE1NDQ3ZWJmYzhiNTlmMzQxMmMyOTFhN2U4OWI5OGQxMDA3NDNkZjhlMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.R8dLkxSkdvVPcLzWRJHJGA_iVG9BFHE4Hl31rM_t8k4">

It's very good, i have 20 Mbps in Fortnite. Thanks.

**Closed as completed** 2024-12-05 14:58 UTC
