### ISSUE TITLE
[Bug] Remote play fail with Edge on Mac

### ISSUE THREAD

**Issue by flewmaple** [redphx/better-xcloud#190] opened 2023-12-26 06:41 UTC
- Device: Macbook Air
 - OS: MaxOS 14.1
 - Browser: Edge
 - Browser Version:120.0.2210.91 
 - Better xCloud Version:2.1.2

Hi
I tried many times to remote my Xbox series x with edge on Mac, but after the rocket animation it just launch the Fortnite cloud gaming. 

But in same Macbook Air, Better xCloud setting and internet situation, it could remote to my home Xbox successfully with Safari. 

The keyboard and mouse support still not ready, so I think there have some need to remote Xbox with Edge and the MK support expansion.

Please check this situation. Thanks.
 
...
![image](https://github.com/redphx/better-xcloud/assets/122140827/5016558f-f25f-441d-987f-4b6f040cd0cb)

<img width="1235" alt="image" src="https://github.com/redphx/better-xcloud/assets/122140827/5e4a2c5f-c267-489e-bd70-4b52a741a46e">

**Comment by flewmaple** [comment] 2023-12-27 03:17
Okay 
I found the problem, just disable the expansion "Keyboard & Mouse for Xbox xCloud", than the Remote-Play can link to my Xbox successfully.

When I enable this expansion, the Remote-Play will launch Fortnite 100%. 

![image](https://github.com/redphx/better-xcloud/assets/122140827/81a009ae-99f2-4dc6-a4bd-9b2dd6656d4d)

**Comment by RoligKanin** [comment] 2023-12-29 09:43
@flewmaple Thank you for that discovery :)
Disabling the extension fixed the black screens (and crash) and fortnite randomly starting, both in Edge and Chrome.

**Comment by redphx** [comment] 2023-12-29 10:33
@flewmaple @RoligKanin  

I'm gonna close this issue since it was caused by another extension.  

I'm implementing the MKB feature for Better xCloud. You can help me test it with [this version](https://github.com/redphx/better-xcloud/issues/98#issuecomment-1866075541). Thanks.

**Closed as not planned by redphx** 2023-12-29 10:33 UTC
Labels: bug
