### ISSUE TITLE
[Bug] Steam Deck low/unstable fps WebGL2

### ISSUE THREAD

**Issue by Regnuss** [redphx/better-xcloud#470] opened 2024-07-31 19:26 UTC
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [X] xCloud officially supports my country/region.
- [ ] The bug doesn't happen when I disable Better xCloud script.
- [ ] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Other

### Device

Steam Deck

### Operating System

SteamOS / Linux

### Android app/Browser Version

both Chrome and Edge, linux

### Better xCloud Version

3.5.1

### Reproduction Steps

If you change to WebGL2, the fps constantly jumps between 30fps/50fps, super unstable and pretty much unplayable. It does look better than the default renderer, but runs bad. In the Steam Deck performance overlay it kinda looks like the SD even uses less power than with the default renderer. (lower cpu/gpu usage, similar battery life ~7w). Lowering or increasing the gpu mhz does not change anything. (lower = more cpu power if needed / higher = more gpu)

The default renderer does not have any issues, stable 60fps. But does not look as good and the sharpening even on setting 1 is to much in my opinion. 

Happens in Edge and Chrome (linux).

**Comment by redphx** [comment] 2024-07-31 21:17
Does it happen when sharpness value is Off?

**Comment by Regnuss** [comment] 2024-08-01 00:34
> Does it happen when sharpness value is Off?

Yes, and using sharpening does not decrease performance. It runs the same with or without sharpening. (webgl2)

**Comment by redphx** [comment] 2024-08-01 00:38
so this is a problem with WebGL2, not the shader.  
This issue is a duplicate of #433, so let's move to there.

**Closed as completed by redphx** 2024-08-01 00:38 UTC
Labels: bug

**Comment by redphx** [comment] 2024-08-01 01:07
chrome://settings/system  

Did you have this setting enabled?

<img width="722" alt="image" src="https://github.com/user-attachments/assets/ff8e6b23-98dd-4f95-a623-8d4b7d369326">

**Comment by Regnuss** [comment] 2024-08-01 13:51
> chrome://settings/system
> 
> Did you have this setting enabled?
> 

Yes, its enabled. 

I now also tried Firefox, runs way better BUT it locks at 90fps instead of 60fps (OLED 90hz) and the Steam Deck gets quite hot/loud + uses >12w instead of 7w. The CPU runs at max speed (3.5GHz).
